// Package policy_definitions provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package policy_definitions

// PolicyDefinitionBean defines model for PolicyDefinitionBean.
type PolicyDefinitionBean struct {
	Deleted     *bool                           `json:"deleted,omitempty"`
	Description *string                         `json:"description,omitempty"`
	Form        *string                         `json:"form,omitempty"`
	FormType    *string                         `json:"formType,omitempty"`
	Icon        *string                         `json:"icon,omitempty"`
	Id          *string                         `json:"id,omitempty"`
	Name        *string                         `json:"name,omitempty"`
	PluginId    *int64                          `json:"pluginId,omitempty"`
	PolicyImpl  *string                         `json:"policyImpl,omitempty"`
	Templates   *[]PolicyDefinitionTemplateBean `json:"templates,omitempty"`
}

// PolicyDefinitionSummaryBean defines model for PolicyDefinitionSummaryBean.
type PolicyDefinitionSummaryBean struct {
	Description *string `json:"description,omitempty"`
	FormType    *string `json:"formType,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	Id          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	PluginId    *int64  `json:"pluginId,omitempty"`
	PolicyImpl  *string `json:"policyImpl,omitempty"`
}

// PolicyDefinitionTemplateBean defines model for PolicyDefinitionTemplateBean.
type PolicyDefinitionTemplateBean struct {
	Language *string `json:"language,omitempty"`
	Template *string `json:"template,omitempty"`
}

// UpdatePolicyDefinitionBean defines model for UpdatePolicyDefinitionBean.
type UpdatePolicyDefinitionBean struct {
	Description *string `json:"description,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// Create2JSONBody defines parameters for Create2.
type Create2JSONBody PolicyDefinitionBean

// Update1JSONBody defines parameters for Update1.
type Update1JSONBody UpdatePolicyDefinitionBean

// Create2RequestBody defines body for Create2 for application/json ContentType.
type Create2JSONRequestBody Create2JSONBody

// Update1RequestBody defines body for Update1 for application/json ContentType.
type Update1JSONRequestBody Update1JSONBody

