// Package actions provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package actions

// ActionBean defines model for ActionBean.
type ActionBean struct {
	EntityId       *string `json:"entityId,omitempty"`
	EntityVersion  *string `json:"entityVersion,omitempty"`
	OrganizationId *string `json:"organizationId,omitempty"`
	Type           *string `json:"type,omitempty"`
}

// PostActionJSONBody defines parameters for PostAction.
type PostActionJSONBody ActionBean

// PostActionRequestBody defines body for PostAction for application/json ContentType.
type PostActionJSONRequestBody PostActionJSONBody

