// Package search provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package search

import (
	"time"
)

// ApiNamespaceBean defines model for ApiNamespaceBean.
type ApiNamespaceBean struct {
	Current     *bool   `json:"current,omitempty"`
	Name        *string `json:"name,omitempty"`
	OwnedByUser *bool   `json:"ownedByUser,omitempty"`
}

// ApiSummaryBean defines model for ApiSummaryBean.
type ApiSummaryBean struct {
	CreatedOn        *time.Time `json:"createdOn,omitempty"`
	Description      *string    `json:"description,omitempty"`
	Id               *string    `json:"id,omitempty"`
	Name             *string    `json:"name,omitempty"`
	OrganizationId   *string    `json:"organizationId,omitempty"`
	OrganizationName *string    `json:"organizationName,omitempty"`
}

// AvailableApiBean defines model for AvailableApiBean.
type AvailableApiBean struct {
	DefinitionType     *string   `json:"definitionType,omitempty"`
	DefinitionUrl      *string   `json:"definitionUrl,omitempty"`
	Description        *string   `json:"description,omitempty"`
	Endpoint           *string   `json:"endpoint,omitempty"`
	EndpointType       *string   `json:"endpointType,omitempty"`
	Icon               *string   `json:"icon,omitempty"`
	Id                 *string   `json:"id,omitempty"`
	Internal           *bool     `json:"internal,omitempty"`
	Name               *string   `json:"name,omitempty"`
	Namespace          *string   `json:"namespace,omitempty"`
	RouteDefinitionUrl *string   `json:"routeDefinitionUrl,omitempty"`
	RouteEndpoint      *string   `json:"routeEndpoint,omitempty"`
	Tags               *[]string `json:"tags,omitempty"`
}

// ClientSummaryBean defines model for ClientSummaryBean.
type ClientSummaryBean struct {
	Description      *string `json:"description,omitempty"`
	Id               *string `json:"id,omitempty"`
	Name             *string `json:"name,omitempty"`
	NumContracts     *int32  `json:"numContracts,omitempty"`
	OrganizationId   *string `json:"organizationId,omitempty"`
	OrganizationName *string `json:"organizationName,omitempty"`
}

// OrderByBean defines model for OrderByBean.
type OrderByBean struct {
	Ascending *bool   `json:"ascending,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// OrganizationSummaryBean defines model for OrganizationSummaryBean.
type OrganizationSummaryBean struct {
	Description *string `json:"description,omitempty"`
	Id          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	NumApis     *int32  `json:"numApis,omitempty"`
	NumClients  *int32  `json:"numClients,omitempty"`
	NumMembers  *int32  `json:"numMembers,omitempty"`
}

// PagingBean defines model for PagingBean.
type PagingBean struct {
	Page     *int32 `json:"page,omitempty"`
	PageSize *int32 `json:"pageSize,omitempty"`
}

// RoleBean defines model for RoleBean.
type RoleBean struct {
	AutoGrant   *bool      `json:"autoGrant,omitempty"`
	CreatedBy   *string    `json:"createdBy,omitempty"`
	CreatedOn   *time.Time `json:"createdOn,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *string    `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Permissions *[]string  `json:"permissions,omitempty"`
}

// SearchCriteriaBean defines model for SearchCriteriaBean.
type SearchCriteriaBean struct {
	Filters *[]SearchCriteriaFilterBean `json:"filters,omitempty"`
	OrderBy *OrderByBean                `json:"orderBy,omitempty"`
	Paging  *PagingBean                 `json:"paging,omitempty"`
}

// SearchCriteriaFilterBean defines model for SearchCriteriaFilterBean.
type SearchCriteriaFilterBean struct {
	Name     *string `json:"name,omitempty"`
	Operator *string `json:"operator,omitempty"`
	Value    *string `json:"value,omitempty"`
}

// SearchResultsBeanApiSummaryBean defines model for SearchResultsBeanApiSummaryBean.
type SearchResultsBeanApiSummaryBean struct {
	Beans     *[]ApiSummaryBean `json:"beans,omitempty"`
	TotalSize *int32            `json:"totalSize,omitempty"`
}

// SearchResultsBeanAvailableApiBean defines model for SearchResultsBeanAvailableApiBean.
type SearchResultsBeanAvailableApiBean struct {
	Beans     *[]AvailableApiBean `json:"beans,omitempty"`
	TotalSize *int32              `json:"totalSize,omitempty"`
}

// SearchResultsBeanClientSummaryBean defines model for SearchResultsBeanClientSummaryBean.
type SearchResultsBeanClientSummaryBean struct {
	Beans     *[]ClientSummaryBean `json:"beans,omitempty"`
	TotalSize *int32               `json:"totalSize,omitempty"`
}

// SearchResultsBeanOrganizationSummaryBean defines model for SearchResultsBeanOrganizationSummaryBean.
type SearchResultsBeanOrganizationSummaryBean struct {
	Beans     *[]OrganizationSummaryBean `json:"beans,omitempty"`
	TotalSize *int32                     `json:"totalSize,omitempty"`
}

// SearchResultsBeanRoleBean defines model for SearchResultsBeanRoleBean.
type SearchResultsBeanRoleBean struct {
	Beans     *[]RoleBean `json:"beans,omitempty"`
	TotalSize *int32      `json:"totalSize,omitempty"`
}

// SearchResultsBeanUserSearchResult defines model for SearchResultsBeanUserSearchResult.
type SearchResultsBeanUserSearchResult struct {
	Beans     *[]UserSearchResult `json:"beans,omitempty"`
	TotalSize *int32              `json:"totalSize,omitempty"`
}

// UserSearchResult defines model for UserSearchResult.
type UserSearchResult struct {
	FullName *string `json:"fullName,omitempty"`
	Username *string `json:"username,omitempty"`
}

// SearchCriteriaBeanRequestBody defines model for SearchCriteriaBeanRequestBody.
type SearchCriteriaBeanRequestBody SearchCriteriaBean

// SearchApiCatalog1RequestBody defines body for SearchApiCatalog1 for application/json ContentType.
type SearchApiCatalog1JSONRequestBody SearchCriteriaBeanRequestBody

// SearchApis1RequestBody defines body for SearchApis1 for application/json ContentType.
type SearchApis1JSONRequestBody SearchCriteriaBeanRequestBody

// SearchClients1RequestBody defines body for SearchClients1 for application/json ContentType.
type SearchClients1JSONRequestBody SearchCriteriaBeanRequestBody

// SearchOrgs1RequestBody defines body for SearchOrgs1 for application/json ContentType.
type SearchOrgs1JSONRequestBody SearchCriteriaBeanRequestBody

// SearchRoles1RequestBody defines body for SearchRoles1 for application/json ContentType.
type SearchRoles1JSONRequestBody SearchCriteriaBeanRequestBody

// SearchUsers1RequestBody defines body for SearchUsers1 for application/json ContentType.
type SearchUsers1JSONRequestBody SearchCriteriaBeanRequestBody

