// Package plugins provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package plugins

import (
	"time"
)

// NewPluginBean defines model for NewPluginBean.
type NewPluginBean struct {
	ArtifactId  *string `json:"artifactId,omitempty"`
	Classifier  *string `json:"classifier,omitempty"`
	Description *string `json:"description,omitempty"`
	GroupId     *string `json:"groupId,omitempty"`
	Name        *string `json:"name,omitempty"`
	Type        *string `json:"type,omitempty"`
	Upgrade     *bool   `json:"upgrade,omitempty"`
	Version     *string `json:"version,omitempty"`
}

// PluginBean defines model for PluginBean.
type PluginBean struct {
	ArtifactId  *string    `json:"artifactId,omitempty"`
	Classifier  *string    `json:"classifier,omitempty"`
	CreatedBy   *string    `json:"createdBy,omitempty"`
	CreatedOn   *time.Time `json:"createdOn,omitempty"`
	Deleted     *bool      `json:"deleted,omitempty"`
	Description *string    `json:"description,omitempty"`
	GroupId     *string    `json:"groupId,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Type        *string    `json:"type,omitempty"`
	Version     *string    `json:"version,omitempty"`
}

// PluginSummaryBean defines model for PluginSummaryBean.
type PluginSummaryBean struct {
	ArtifactId  *string    `json:"artifactId,omitempty"`
	Classifier  *string    `json:"classifier,omitempty"`
	CreatedBy   *string    `json:"createdBy,omitempty"`
	CreatedOn   *time.Time `json:"createdOn,omitempty"`
	Description *string    `json:"description,omitempty"`
	GroupId     *string    `json:"groupId,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Type        *string    `json:"type,omitempty"`
	Version     *string    `json:"version,omitempty"`
}

// PolicyDefinitionSummaryBean defines model for PolicyDefinitionSummaryBean.
type PolicyDefinitionSummaryBean struct {
	Description *string `json:"description,omitempty"`
	FormType    *string `json:"formType,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	Id          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	PluginId    *int64  `json:"pluginId,omitempty"`
	PolicyImpl  *string `json:"policyImpl,omitempty"`
}

// Create1JSONBody defines parameters for Create1.
type Create1JSONBody NewPluginBean

// Create1RequestBody defines body for Create1 for application/json ContentType.
type Create1JSONRequestBody Create1JSONBody

