// Package system provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package system

// SystemStatusBean defines model for SystemStatusBean.
type SystemStatusBean struct {
	BuiltOn     *string `json:"builtOn,omitempty"`
	Description *string `json:"description,omitempty"`
	Id          *string `json:"id,omitempty"`
	MoreInfo    *string `json:"moreInfo,omitempty"`
	Name        *string `json:"name,omitempty"`
	Up          *bool   `json:"up,omitempty"`
	Version     *string `json:"version,omitempty"`
}

// ExportData1Params defines parameters for ExportData1.
type ExportData1Params struct {
	Download *string `json:"download,omitempty"`
}

