// Package gateways provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package gateways

import (
	"time"
)

// GatewayBean defines model for GatewayBean.
type GatewayBean struct {
	Configuration *string    `json:"configuration,omitempty"`
	CreatedBy     *string    `json:"createdBy,omitempty"`
	CreatedOn     *time.Time `json:"createdOn,omitempty"`
	Description   *string    `json:"description,omitempty"`
	Id            *string    `json:"id,omitempty"`
	ModifiedBy    *string    `json:"modifiedBy,omitempty"`
	ModifiedOn    *time.Time `json:"modifiedOn,omitempty"`
	Name          *string    `json:"name,omitempty"`
	Type          *string    `json:"type,omitempty"`
}

// GatewayEndpointSummaryBean defines model for GatewayEndpointSummaryBean.
type GatewayEndpointSummaryBean struct {
	Endpoint *string `json:"endpoint,omitempty"`
}

// GatewaySummaryBean defines model for GatewaySummaryBean.
type GatewaySummaryBean struct {
	Description *string `json:"description,omitempty"`
	Id          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Type        *string `json:"type,omitempty"`
}

// GatewayTestResultBean defines model for GatewayTestResultBean.
type GatewayTestResultBean struct {
	Detail  *string `json:"detail,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// NewGatewayBean defines model for NewGatewayBean.
type NewGatewayBean struct {
	Configuration *string `json:"configuration,omitempty"`
	Description   *string `json:"description,omitempty"`
	Name          *string `json:"name,omitempty"`
	Type          *string `json:"type,omitempty"`
}

// UpdateGatewayBean defines model for UpdateGatewayBean.
type UpdateGatewayBean struct {
	Configuration *string `json:"configuration,omitempty"`
	Description   *string `json:"description,omitempty"`
	Type          *string `json:"type,omitempty"`
}

// NewGatewayBeanRequestBody defines model for NewGatewayBeanRequestBody.
type NewGatewayBeanRequestBody NewGatewayBean

// PutGatewayByIdJSONBody defines parameters for PutGatewayById.
type PutGatewayByIdJSONBody UpdateGatewayBean

// PostGatewaysRequestBody defines body for PostGateways for application/json ContentType.
type PostGatewaysJSONRequestBody NewGatewayBeanRequestBody

// PutGatewaysRequestBody defines body for PutGateways for application/json ContentType.
type PutGatewaysJSONRequestBody NewGatewayBeanRequestBody

// PutGatewayByIdRequestBody defines body for PutGatewayById for application/json ContentType.
type PutGatewayByIdJSONRequestBody PutGatewayByIdJSONBody

