// Package roles provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package roles

import (
	"time"
)

// NewRoleBean defines model for NewRoleBean.
type NewRoleBean struct {
	AutoGrant   *bool     `json:"autoGrant,omitempty"`
	Description *string   `json:"description,omitempty"`
	Name        *string   `json:"name,omitempty"`
	Permissions *[]string `json:"permissions,omitempty"`
}

// RoleBean defines model for RoleBean.
type RoleBean struct {
	AutoGrant   *bool      `json:"autoGrant,omitempty"`
	CreatedBy   *string    `json:"createdBy,omitempty"`
	CreatedOn   *time.Time `json:"createdOn,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *string    `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Permissions *[]string  `json:"permissions,omitempty"`
}

// UpdateRoleBean defines model for UpdateRoleBean.
type UpdateRoleBean struct {
	AutoGrant   *bool     `json:"autoGrant,omitempty"`
	Description *string   `json:"description,omitempty"`
	Name        *string   `json:"name,omitempty"`
	Permissions *[]string `json:"permissions,omitempty"`
}

// Create3JSONBody defines parameters for Create3.
type Create3JSONBody NewRoleBean

// Update2JSONBody defines parameters for Update2.
type Update2JSONBody UpdateRoleBean

// Create3RequestBody defines body for Create3 for application/json ContentType.
type Create3JSONRequestBody Create3JSONBody

// Update2RequestBody defines body for Update2 for application/json ContentType.
type Update2JSONRequestBody Update2JSONBody

